---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false
configure_dock: false
configure_sudoers: false

configure_dock: true
dockitems_remove: []
 - Finder
 - Launchpad
 - Firefox
 - Messages
 - Spotify
 - Mail
 - Calendar
 - Reminers
 - Notes
 - Settings
 - Activity monitor
 - Terminal
 - visual-studio-code

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - sqlite
  - mysql
  - php
  - python
  - ssh-copy-id
  - pv
  - wget
  - brew-cask

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - spotify
  - google-drive
  - parallels
  - visual-studio
  - visual-studio-code
  - discord
  - signal
  - vagrant

mas_installed_apps: []
mas_email: ""
mas_password: ""

composer_packages: []
gem_packages: []
npm_packages: []
pip_packages: []

configure_sublime: false

post_provision_tasks: []
